# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_propiedad_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='img',
            field=models.BinaryField(),
        ),
    ]
