# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180201_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='img',
            field=models.ImageField(default='uploads/f1.png', upload_to='uploads/'),
        ),
    ]
