# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180206_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='uploads/f1.png', upload_to='uploads/%d-%m-%y/%H_%M_%S')),
            ],
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='img',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='imagen',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
