# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180211_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.UsuarioGratuito'),
            preserve_default=False,
        ),
    ]
