# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180215_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='propietario',
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='descripcio',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
