# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180215_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='descripcio',
        ),
    ]
