# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='estrella',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.RemoveField(
            model_name='usuariogratuito',
            name='idUser',
        ),
        migrations.DeleteModel(
            name='Broker',
        ),
        migrations.DeleteModel(
            name='Estrella',
        ),
        migrations.DeleteModel(
            name='UsuarioGratuito',
        ),
    ]
